# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake
permissions: 
  contents: write

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

  workflow_dispatch:  # Allows manual execution from the Actions tab

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Step 2: Generate the Snake animation
      - name: Generate GitHub Contributions Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Show the status of the build for debugging
      - name: Check Git Status
        run: git status
          
      # Step 4: Push the changes to the output branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Use a Personal Access Token instead of GITHUB_TOKEN
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update Snake animation [skip ci]"
          force_orphan: true
